name: flutter_inner_printer
description: This is a printer product written by cudev
homepage: https://github.com/phanbaohuy96/flutter-inner-printer


version: 1.0.7

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=1.12.0"

dependencies:
  flutter:
    sdk: flutter
  intl: 
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  plugin:
    platforms:
      android:
        package: com.flutter_inner_printer.b08
        pluginClass: FlutterInnerPrinterPlugin

